### ISSUE TITLE
Update to minGW installation

### ISSUE THREAD

**Issue by mintyc** [sandstorm-io/capnproto#176]
Using MinGW and cmake to build compiler tools on windows

Maybe add that tip to the installation page
e.g. In the Windows Install from Git section add

> MinGW can be found in various forms. Try
> http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/
> and pick 4.9.2/posix/seh variant

Alternatively with MinGW64 and cmake installed on windows and on the
PATH, create an out of source build

mkdir build
cd build
cmake -G "MinGW Makefiles" ../c++
make capnp_tool capnpc_cpp capnpc_capnp
cd src\capnp
strip capnp.exe
strip capnpc-c++.exe
strip capnpc-capnp.exe

You may need to replace 'make' with 'mingw32-make' if you haven't
aliased 'make' to that file already.
<

**Comment by kentonv** [comment]
Cleaning up old issues.

Not sure if this issue is still relevant. Probably the version numbers would have changed, at least. I'm inclined to avoid documenting general usage tips about MinGW since there are lots of different valid ways to use it and different developers will have their preferences. (E.g. I usually use it with the automake files, not cmake.)

So, I'm closing this issue.
