### ISSUE TITLE
Consider renaming the new $persistent annotation

### ISSUE THREAD

**Issue by zombiezen** [sandstorm-io/capnproto#184]
Feel free to mark this as WAI, but for code generators where there are case transformations (such as go-capnproto), the Persistent interface and $persistent annotation have the same name.  Could one or the other be renamed so that they have distinct case-insensitive names?

**Comment by kentonv** [comment]
Hi Ross,

In general it is the responsibility of a code generator to generate working code for any valid .capnp input, perhaps by renaming things in the case of conflicts.

OTOH, it is generally infeasible for code generators to actually consider and avoid every possible way that the code could end up broken. In cases where name conflicts come up for a specific code generator, the general recommendation is for that code generator to define a "rename" annotation which allows people to give the offending declaration a different name for that specific language. This lets the build be fixed in that language without breaking anyone else who already depends on the originally-chosen name.

It looks like go-capnproto doesn't currently declare any such annotation. If it did, we could use it, although this creates another problem with dependencies. Hmm...

@glycerine any thoughts?

**Comment by glycerine** [comment]
I'm not opposed to adding a rename feature; but don't have time to do it myself. For it's worth, I put a similar feature in BamBam to allow users to do name conflict resolution on their own.

For immediate progress, perhaps the horrible hack of special case-handling of Persistent or $persistent would suffice for now.

**Comment by dwrensha** [comment]
I'm unclear about where the actual problem arises in the particular case of Persistent / $persistent. In my understanding, annotations are only used during code generation or reflection. They don't ever show up in the generated code, so a name collision isn't possible. Am I missing something?

**Comment by zombiezen** [comment]
Having a renaming annotation would definitely work; I'll try to write up a PR.

@dwrensha: the issue is that the go-capnproto code generator creates a constant for each annotation that is the ID.  Since Go mandates that all public symbols must begin with an uppercase character, go-capnproto capitalizes the first character of any name it generates (thus annotation `persistent` maps to `Persistent` and interface `Persistent` also to `Persistent`).

**Comment by kentonv** [comment]
Out of curiosity, what are you doing with `persistent.capnp` in Go? Is Go getting RPC support? :)

**Comment by zombiezen** [comment]
I have been tinkering with support as a weekend project. :)  My fork of go-capnproto supports generating interfaces.  I have a rudimentary mock-up of the RPC system that I used to test the interface support, but it doesn't support embargoes or properly handle releasing imports/exports.

**Comment by zombiezen** [comment]
Since the resolution is to rename it from the Go side, feel free to close this issue as "working as intended".  Not quite sure how to solve the dependency issue, although you could copy the annotation ID inline in `persistent.capnp`.

**Comment by kentonv** [comment]
> you could copy the annotation ID inline in persistent.capnp.

Unfortunately, no, because if the compiler sees to different declarations with the same ID in one run it'll get upset.

Probably the easiest thing for now would be for the Go generator to have some hard-coded renames for well-known `.capnp` files.

Longer-term, we need a general way for one project to add annotations to another project's files, without editing them directly. All the ideas I've come up with are fairly involved, though.

Anyway, closing this.
