### ISSUE TITLE
Consider unifying unions and enums

### ISSUE THREAD

**Issue by vks** [sandstorm-io/capnproto#185]
As observed in #2, enums are currently somewhat redundant to unions of voids. Maybe capnproto could be simplified by unifying them?

A problem is that unions are always fields, and enums are always types. (See the [description of the schema language](https://capnproto.org/language.html) for the reason.) I think it could make sense to support both independent unions and unions as fields.

```
my_enum :union {
    variant1 @0;
    variant2 @1;
}
```

could be sugar for

```
my_enum :union {
    variant1 @0 :Void;
    variant2 @1 :Void;
}
```

This should make explicit use of the void type unnecessary. Union could be renamed to enum.

**Comment by kentonv** [comment]
Hi Vinzent,

The type theorist in me really likes the elegance of unifying these two things.

But, there's a practical problem: `enum` defines a type which can be reused in many places and is known to be strictly 16 bits. As you noted, the [documentation for unions](https://capnproto.org/language.html#unions) explains why `union` does not declare a type, but rather acts as a field with a one-off type. There are lots of use cases for reusable enum types. Using a reusable union (that is, a struct that just contains a union) would use 8x as much space on the wire as a simple enum (8 bytes for the pointer and at least 8 bytes for the object it points to), which would be unfortunate.

I do agree that in cases where an enum is declared just to be used in one place, it makes sense to use a union instead, so that you can easily declare fields that only apply to one branch of the union. Being able to omit the `:Void` makes things a bit more concise but could also add confusion, so I'm not sure if that is worthwhile at the moment.

**Comment by vks** [comment]
Isn't that a compiler problem? The compiler could be able to optimize reusable unions with `Void`s only to be represented by a 16 bit int.

I think getting rid of `Void` only makes sense when unifying unions and enums. This is kind of what Rust did, and it works pretty well there. 

On the other hand, I understand that there is little to be gained by such a backwards-incompatible change that presumably needs non-trivial work to make enums as efficient as they are now.

**Comment by kentonv** [comment]
In any regular programming language it would be a compiler problem, but for Cap'n Proto we worry about compatibility with future versions of the protocol. A union with only voids today might contain new, non-void fields in the future, and programs compiled with old and new versions of the protocol need to be able to talk to each other.

**Comment by vks** [comment]
Couldn't you sacrifice one bit of the pointer to the union object as a flag for storing `Void`-only unions in the pointer? (Kind of like a small string optimization.) I think this would be future-proof to the addition of non-`Void` fields.

This would add a branch for every union pointer lookup and still be 4 times less space efficient than the current enums though.

**Comment by kentonv** [comment]
I think 8 bytes is still too much here, and we actually don't really have any bits to spare in the pointer encoding, which is pretty densely packed. Also, Cap'n Proto is already widely deployed in production so it's too late for these kinds of backwards-incompatible changes (too bad, because there are a few other things I would tweak otherwise...).

**Comment by vks** [comment]
Are you saying the 64 - 48 = 16 bits unused by AMD64 are already used by Cap'n Proto?
Could there be a backwards-incompatible Cap'n Proto 2.0 in a few years?

**Comment by kentonv** [comment]
> Are you saying the 64 - 48 = 16 bits unused by AMD64 are already used by Cap'n Proto?

Yes, these are not native pointers. In fact, 34 of the bits are used for type info. See: https://capnproto.org/encoding.html

> Could there be a backwards-incompatible Cap'n Proto 2.0 in a few years?

There would have to be a hugely compelling reason, otherwise the cost of switching wouldn't be worth it. Google, for example, has been using protobufs for 15 years even though inefficiencies were recognized in the format pretty early on, because the cost of switching to something new would be astronomical for them, given all the data and infrastructure they've built around it.

While there are a few things I'm not completely happy with in Cap'n Proto as-is, they are relatively minor. For example, I don't like that far pointers use an absolute segment number rather than a relative offset -- an offset would have allowed embedding one Cap'n Proto message into another without a copy, by annexing its segments. But at this point it probably makes more sense to find a way to implement that without changing the existing format; there are a few hacks that could work, they are just uglier than the relative-segment-number approach.

**Comment by kaos** [comment]
@kentonv I would suggest looking into the possibility to add a version field to the message header, along with the segment table, in order to be able to introduce backwards incompatible changes.

That way, you would give end users the choice of which version to use, depending on their use case, by having a flag or annotation or something in the schema files or passed to the compiler at compile time to toggle select version (effectively toggling these features on/off) or some such.. I think you get the general idea.

**Comment by kentonv** [comment]
Cleaning up old issues. This was an interesting discussion but ultimately I don't think there's anything actionable. We will have to live with imperfection.
