### ISSUE TITLE
integer overflows in output path (not remotely exploitable)

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/capnproto#195]
This test fails for me, both on 32-bit and 64-bit systems:

``` c++
TEST(Encoding, LongList) {
  MallocMessageBuilder builder;

  auto root = builder.initRoot<TestAllTypes>();
  uint length = 1 << 27;
  auto list = root.initUInt64List(length);
  for (int ii = 0; ii < length; ++ii) {
    list.set(ii, ii);
  }
  for (int ii = 0; ii < length; ++ii) {
    ASSERT_EQ(list[ii], ii);
  }
}
```

```
capnp/encoding-test.c++:46: failed: expected (list[ii]) == (ii); list[ii] = 67108864; ii = 0
```

I think the problem is that integer overflows are possible [here](https://github.com/sandstorm-io/capnproto/blob/1859b718bc04fa4325a60fecf6e694842860dabd/c%2B%2B/src/capnp/layout.h#L1000) and [here](https://github.com/sandstorm-io/capnproto/blob/1859b718bc04fa4325a60fecf6e694842860dabd/c%2B%2B/src/capnp/layout.h#L1030).

It seems like it should also be possible to craft an input that would cause a segfault, but I haven't succeeded in doing that yet.

**Comment by kentonv** [comment]
Yes, there are currently some known integer overflows on the output path. The work-in-progress [overflow-safe branch](https://github.com/sandstorm-io/capnproto/tree/overflow-safe) should turn all these into exceptions, once we finish it.

Since this issue affects output, not input, it cannot be exploited remotely and therefore we don't consider it a security issue.

That said, please report possible security issues privately in the future.

**Comment by kentonv** [comment]
These issues should be fixed now that the overflow-safe branch was merged, but I should add your test somewhere to be sure.
