### ISSUE TITLE
compression suggestion(Blosc)

### ISSUE THREAD

**Issue by sbant** [sandstorm-io/capnproto#224]
In the roadmap page there is "Snappy integration" for compression.

I'd suggest consider Blosc as the compression library for capnp.
http://blosc.org/
https://github.com/Blosc/c-blosc

Advantage:
MIT license
easy integration(C language)
optimized for binary data
can be faster than `memcpy()`
pre-filters(shuffling bytes in binary blocks) for better binary compress
multi compressors integrated include Snappy(BloscLZ, LZ4, LZ4HC, Snappy, Zlib)
Ready For Production Use(use in PyTables and Pandas)

**Comment by kentonv** [comment]
Thanks, I'll take a look when I get a chance.

Note that using a non-mainstream compression library may be tricky in that we don't want to create obstacles to supporting Cap'n Proto in languages that can't call into a C library, and it doesn't look like they have a lot of language support yet. Also, we'd want to make sure anything we use has had sufficient security review.

(FWIW, that point from the roadmap seems outdated: it ought to say LZ4 rather than Snappy.)

**Comment by kentonv** [comment]
Cleaning up old issues.

I think if we officially support some form of compression, it will probably be LZ4, due to wide availability and being well-tested (e.g. for security issues). But we do want to make sure it's always easy for an app to hook in its own preferred compression, so that people can hook in more experimental things if they want.
