### ISSUE TITLE
Ekam rules are not installed

### ISSUE THREAD

**Issue by maurer** [sandstorm-io/capnproto#229]
Currently, ekam projects using capnproto need the source at compile time in order to access `capnpc.ekam-rule`.

Perhaps installing it in a way similar to how CMake modules are installed would allow less rebuilding and easier packaging of software built against capnproto.

**Comment by kentonv** [comment]
Yeah, Ekam is very much designed with the intent that you build your dependencies from source, and that's what we do with Sandstorm. It works particularly well for us since I'm often developing Cap'n Proto and Sandstorm at the same time, and having to install Cap'n Proto after each change is tiresome.

The `capnp.ekam-rule` actually can't even work in any other mode as-is, as it is set up to assume that the `capnp` tool is built from the repo. So it's not just a matter of installing, but actually writing a rule that works stand-alone.

If we did have an `.ekam-rule` designed to use the system-installed `.capnp`, then I would suggest copying (or symlinking) said rule into your source tree rather than "installing" it. That's generally the "ekam way": symlinking in things from your "deps" directory. Look closely at Sandstorm for an example, especially the `src/sodium` directory. :)

There is a lot of work to do to make Ekam understand the concept of installed dependencies better. I don't expect I'll be able to work on any of it any time soon, unfortunately.

**Comment by kentonv** [comment]
Closing this capnp issue since this is more of an Ekam issue, and a very open question.
