### ISSUE TITLE
Cap'n Proto Truck Factor

### ISSUE THREAD

**Issue by gavelino** [sandstorm-io/capnproto#231]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Cap'n Proto** and obtained a value of **1**.

The developer responsible for this TF is:

Kenton Varda - author of 98% of the files 

To validate our results, we would like to ask **Cap'n Proto** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Cap'n Proto**?

(b) Do you agree that **Cap'n Proto** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(b) Does **Cap'n Proto** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by kentonv** [comment]
> (a) Do you agree that the listed developer is the main developer of Cap'n Proto?

Yes.

> (b) Do you agree that Cap'n Proto will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

If I won the lottery, it would be _great_ for Cap'n Proto, because then I would devote all my time to coding rather than things like, say, fundraising. Money can't cure my coding addiction. :)

But to answer your question: There are a number of people who understand Cap'n Proto pretty well by virtue of having implemented versions of it in other languages (as separate git repos). Most likely, @dwrensha would take over the main repo. Development would certainly slow down considerably but I don't think it would be a complete loss.

> (b) Does Cap'n Proto have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

The fact that people have implemented it in other languages, as described above. (And maybe the fact that I write a lot of comments?)

**Comment by ocdtrekkie** [comment]
@gavelino You have two (b)s.

Sidebar: This is a really neat thing to study, and it's very relevant/important given the number of poorly-maintained projects out there today.

**Comment by gavelino** [comment]
Thank you. I really appreciated your answers.

**Comment by kaos** [comment]
@ocdtrekkie I agree; :+1: for this research @gavelino :)
