### ISSUE TITLE
C++ compilation error if group in union has the same name as union

### ISSUE THREAD

**Issue by MarPiRK** [sandstorm-io/capnproto#238]
I know that it's really silly way of defining things, but this time I had no other idea in mind to name `group` other than using `union` name.

Here's sample `test.capnp`:

```capnp
@0x8560dc57331b4909;
struct Test {
    asdf :union {
        none @0 :Void;
        asdf :group {
            i1 @1 :Int32;
            i2 @2 :Int32;
        }
    }
}
```

Compiling it with `capnp` doesn't show any errors whatsoever, but C++ compiler throws [this](http://pastebin.com/JXpBgS4N), what basically means that creating group with name `asdf` in union with name `asdf` isn't allowed.

It'd be nice to tell users about it during `capnp compile`.

**Comment by kentonv** [comment]
Hi @MarPiRK,

Thanks for the report.

There are actually a very large number of ways to write Cap'n Proto files that will fail to compile in various languages. It would take quite a bit of effort to track them all down and detect them in advance, for not a whole lot of gain -- people don't actually run into them that often, and people generally figure out what went wrong pretty easily anyhow.

The one big possible problem is that you could write and test a schema using, say, Java, and then only find out much later on that it doesn't compile in C++. By then renaming things might be inconvenient, if a lot of Java code had already been written with the old names. So we provide the `$name` annotation (defined in `/capnp/c++.capnp`) to allow you to rename a single declaration arbitrarily just for the purpose of C++:

    using name = import "/capnp/c++.capnp".name;

    struct Test {
        asdf :union {
            none @0 :Void;
            asdf :group $name("asdf2") {
                i1 @1 :Int32;
                i2 @2 :Int32;
            }
        }
    }

I'm closing this bug because while I agree it would be nice to detect these things earlier, we've concluded that the cost/benefit tradeoff just isn't worth it compared to other things that we could be working on. Sorry!

**Comment by MarPiRK** [comment]
Ok, I see no problem in it at all :) Just thought it'd be nice to report this kind of errors earlier, but I see your point.
Anyways thanks for advice about name annotation.
