### ISSUE TITLE
Protobuf migration tool or technique

### ISSUE THREAD

**Issue by ekg** [sandstorm-io/capnproto#245]
Has anyone developed a method to port c++ based on protobuf to capnp? It looks like a series of find and replace operations will get me most of the way, but I'm curious about peoples experiences.

**Comment by paulproteus** [comment]
I for one haven't, but I do want to say hi Erik! I'm curious about @kentonv 's perspective on this.

**Comment by ekg** [comment]
Hi Asheesh! :waves: I have a ~20k line codebase that'd I'd like to migrate and test, so any timesaving techniques would be very helpful.

One of the biggest frustrations I've had with protobuf is that messages can't be larger than 64MB. In my case we need to be able to handle messages of up to 1TB or there will be a need to implement hacks on serialization and deserialization. I'm also curious if this kind of use pattern is supported by capnp. Is there a max message size?

**Comment by ekg** [comment]
Whoops that last comment isn't entirely clear. Another way of asking is "how hard is it to implement streaming parsers in capnp?"

**Comment by kentonv** [comment]
Much like with protobufs, there is a default enforced message size (I think of 64MB), but you can increase the default (see `capnp::ReaderOptions`). The default exists in part to prevent resource exhaustion attacks, e.g. where someone sends you a gigabyte message when you were only expecting a dozen bytes.

Protobufs had a theoretical maximum message size of 2^31 bytes. Cap'n Proto's max is 2^64 bytes (though note that a particular List, Text, or Data item cannot exceed 512M elements).

Cap'n Proto will, of course, scale much better to large messages since you can use mmap() and read just what you need rather than parsing upfront.

However, note that Cap'n Proto still isn't great for large _mutable_ data. Cap'n Proto messages use an arena allocator, meaning all new objects are allocated at the end of the message, and space is not reclaimed from "freed" objects. If you are writing your 1TB message all at once, this is fine, but if you intended to represent a 1TB database which you regularly modify, then you'll need to break it up into small pieces that you can modify as units.

To answer the original question: Inside Google, a great deal of effort was spent developing tools to automate a migration from Proto1 to Proto2 even though they had nearly-identical APIs. Moving to Cap'n Proto is a much larger jump. Unfortunately I don't think you'll be able to automate it, though you may be able to automate, say, 75% of it. I'm not aware of any tools written for this purpose currently.

**Comment by kentonv** [comment]
I'm going to close this as I don't think a tool for this is likely to be built. That said, if someone wants to work on it, please do get in touch!

**Comment by XplicitComputing** [comment]
> Protobufs had a theoretical maximum message size of 2^31 bytes. Cap'n Proto's max is 2^64 bytes (though note that a particular List, Text, or Data item cannot exceed 512M elements).

Hello, thank you for developing Cap'n Proto. My application is sort-of in no-man's land -- spanning numerical computing and network messaging. Some pretty pictures are available here: www.xplicitcomputing.com . Much effort has gone into our vectorized parallel data format...It's challenging to meet all requirements.
Currently our contiguous data is "medium size" -- few million elements, but there is an industry push towards exa-scale; current goals are greater 10^10 geometric elements. This puts a constraint on topology associativity lists as well as floating-point scalar data. Any chance we could increase the maximum list size beyond 512M in future version of Cap'n Proto? I'm afraid there is no other reasonable way to break up these messages...

**Comment by kentonv** [comment]
@XplicitComputing Unfortunately, there's no way for us to increase the maximum list size without breaking backwards-compatibility, which would be too costly to consider.

**Comment by XplicitComputing** [comment]
@kentonv  thank you much.
Could I branch your sources and create an extended version for scientific computing applications?

**Comment by kentonv** [comment]
@XplicitComputing The code is open source. You are free to do with it as you please (subject to the MIT license).

**Comment by XplicitComputing** [comment]
@kentonv great. Do you think my scope of changes will be confined to converting int's in list.h and calling functions? Or will there need to be changes to infrastructure? Any quick guidance very much appreciated!

**Comment by kentonv** [comment]
@XplicitComputing No, the limitations are fundamental to the encoding itself, not the C++ implementation. See: https://capnproto.org/encoding.html

In particular:
* The encoding of list pointers only allows 29 bits for the list size.
* All objects (such as lists) reside within segments, and the maximum segment size is 4GB. The segment size is limited because all pointer types encode their "offset" component as a 30 bit signed number of words, meaning the maximum distance between a pointer and the object it points at is 2^29 words * 8 bytes/word = 4GB.

To solve these problems you will need to change the way pointers are encoded, which means changing layout.c++. I'm not really sure how best to solve the fact that there just aren't enough bits to encode larger sizes. Maybe you need to invent a new kind of far pointer that points to a special kind of segment?

**Comment by XplicitComputing** [comment]
@kentonv thank you for the information. Something to think about!
