### ISSUE TITLE
IDL: Allow intrinsic IDs

### ISSUE THREAD

**Issue by Downchuck** [sandstorm-io/capnproto#246]
I'd like to see the IDL allow intrinsic IDs, that is, if no ID annotations are present, it can just assume that the order of the fields marks the ID.

```
struct Msg {
 field @0 :Text;
}
```
would be the same as
```
struct Msg {
 field:Text;
}
```

**Comment by kentonv** [comment]
Hi Charles,

Thanks for the feedback!

Unfortunately, experience from Protocol Buffers shows that implicit field numbers are very likely to lead to accidental backwards-incompatible changes. Programmers often like to insert new fields next to related fields rather than on the end, or re-arrange fields for clarity. It's easy to forget that this breaks protocol compatibility (even for people who know better, but especially for newcomers not familiar with how the protocol works), and it's hard to catch this kind of problem in a unit test.

On the other hand, with explicit field numbers, a programmer has to go out of their way to edit the numbers on existing fields to cause a breakage, and it's generally obvious to people that they shouldn't do that. In practice forcing explicit field numbers has proven highly effective at ensuring that protocols remain backwards-compatible as they evolve.

So, this is in fact a deliberate and important design decision, and not something we are likely to change. Sorry!

**Comment by Downchuck** [comment]
Deliberate decisions are fine provided there's room for tooling. I agree
the final output format is swell. Has a magic number just to save you from
horrors.

That said: flatbuf has a nice broken converter from Proto to flatbuf schema
and that's some nice tooling to have.

Give me a little tool action to label my intrinsics, or really just to
convert from the simpler flatbuf .pbs to a capn and I'm in a good place. I
have no problem installing flatc solely to use the converter in a pipeline.

**Comment by kentonv** [comment]
If you write a tool I'm happy to link to it from our docs! But I'm afraid it's unlikely I'll have any time to work on this myself, sorry.
