### ISSUE TITLE
parser complains about a missing ID although the ID is present

### ISSUE THREAD

**Issue by eriksjolund** [sandstorm-io/capnproto#251]
I've encountered a confusing error message when parsing a syntactically incorrect schema file.
This is very low priority but anyway:

The parser complained about a missing ID although the ID was present in the file. It would have been better if the parser would only have complained about line 4 where the syntax error was.

```
user@ubuntu:/tmp$ capnp --version
Cap'n Proto version 0.5.3
user@ubuntu:/tmp$ cat a.capnp
@0xdbb9ad1f14bf0b36;

struct Person {
  name @0 :Text; // A mistake, I should have used # for comments
}
user@ubuntu:/tmp$ capnp compile -oc++ a.capnp
  a.capnp:4:30: error: Parse error.
  a.capnp:1:1: error: File does not declare an ID.  I've generated one for you.  Add this line to your file:  @0xbe52960005d73d32;
user@ubuntu:/tmp$
```

**Comment by kentonv** [comment]
Problem is that when compilation fails in the lexing stage, no parse tree is returned at all. Solution: don't check for the ID if compilation already failed. Or maybe don't complain about the missing ID if the file appears empty.

**Comment by adrianratnapala** [comment]
As it is, the compiler deliberately continues with parsing after a lex error, in case the subsequent errors are useful.  This bug is in tension with that design decision.  I see three possibilities:

1. Continue with the "parse errors after lex errors are useful" philosophy, and mark this as not a bug.
2. Change the philosophy to "parse errors after lex errors are confusing", and skip the whole parse.
3. Suppress the ID-check as special case, but still parse and report all other errors.

My gut instinct is to pefer #2, if only because it simplifies the code.  

#3 only makes sense if there is some reason why an the ID-check errors would be more confusing and less useful than other parse errors.
