### ISSUE TITLE
Block syntax for functions taking code like KJ_DEFER / KJ_ON_SCOPE_*

### ISSUE THREAD

**Issue by mrdomino** [sandstorm-io/capnproto#273]
Using an implementation like that on slide 20 of [the uncaught_exceptions proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4152.pdf) (i.e. an overloaded `operator+` of a functor type), we could write deferred blocks like:

```
KJ_DEFER { code; }
```

instead of the current `KJ_DEFER(code);`. It'd probably be a bit, but not much, more work to also do `KJ_ON_SCOPE_SUCCESS` and `KJ_ON_SCOPE_FAILURE` like this. Is it desirable to have this? If so, I can start on a pull request.

**Comment by kentonv** [comment]
Hmm. Users will have to type a semicolon after the closing brace, that is:

    KJ_DEFER { code; };

This may be unintuitive, since it differs from usual control blocks. Note that `KJ_MAP` works this way, but it also evaluates to a value, which perhaps makes it less surprising.

Note that currently, the following syntax works:

    KJ_DEFER({
      code();
      moreCode();
    });

I guess overall I don't see a huge advantage to avoiding the parentheses here. In retrospect I would perhaps have done it that way had I thought of it originally, but I'm not sure it's worth changing now. I wouldn't want to break existing users, nor do I think it's worth having two different accepted syntaxes (if that's even possible; not sure).

Thoughts?

**Comment by mrdomino** [comment]
Yeah, probably not worth it given that you still need the closing semicolon (I hadn't noticed that). Closing for now.
