### ISSUE TITLE
json data encoding and base64

### ISSUE THREAD

**Issue by katreniak** [sandstorm-io/capnproto#298]
Capnp Json codec serializes binary data as array of bytes. I propose to change the default to base64 to be compatible with [protobuf json encoding](https://developers.google.com/protocol-buffers/docs/proto3#json).

I understand that there is no single standard. And if give application requires specific serialization, it can override the default. But it may be wise to align default with competing technology.

**Comment by kentonv** [comment]
I definitely think we should provide a readily-available `JsonCodec::Handler<Data>` implementation that does base64.

I'm not thrilled with it as a default because:
- The capnp node.js bindings, which convert Cap'n Proto objects to Javascript objects and back, use the Buffer type, which behaves like an array of byte values. Everything else about the node bindings are consistent with JsonCocec.
- base64 encoding/decoding is not readily available in browsers. (atob() and btoa() unfortunately represent binary data as strings which has serious problems.)
- In none of the cases I've used JsonCocec so far would it have been appropriate to use base64 by default.

I would be more inclined, really, to have the default behavior output `null` for all data values or maybe throw an exception, if only to make it clear to people that they need to choose a representation.

**Comment by katreniak** [comment]
Good defaults matter a lot. I believe that array of bytes is much better default than `null`. Thank you, Kenton, for your justification.
