### ISSUE TITLE
Question about fulfiller lifetime

### ISSUE THREAD

**Issue by barakp** [sandstorm-io/capnproto#307]
Hi @kentonv 

Is it ok to assume that the call to fulfiller->fulfill() is synchronous i.e. is it OK to assign a nullptr to a `Maybe<Fulfiller>` right after calling fulfill() ? will the promise callback be called synchronously upon the call to fulfill()?

I'm asking since I'd like to pass the fulfiller as a context to a callback of an asynchronous C function and then when the callback is called fulfill the promise and destruct the fulfiller immediately. Is that the best practice in these cases?

Your help would be much appreciated.

**Comment by kentonv** [comment]
Hi Barak,

> is it OK to assign a nullptr to a Maybe<Fulfiller> right after calling fulfill()?

Yes.

The Fulfiller doesn't actually hold any state of its own; it's basically a pointer to some state owned by the Promise.

> will the promise callback be called synchronously upon the call to fulfill()?

No.

The callback is queued to execute once you return to the event loop. In general, callbacks are never called while another callback is still running, because this can create a lot of confusion.

For example, what if the callback deleted the object that fulfilled it? If it happened synchronously during `fulfill()`, then after `fulfill()` returned you might be left with a `this` pointer pointing to an object that no longer exists, which is really confusing.

**Comment by barakp** [comment]
Thank you!
