### ISSUE TITLE
How to post / dispatch handler into EventLoop?

### ISSUE THREAD

**Issue by katreniak** [sandstorm-io/capnproto#320]
I am looking for a way how to post handler from other threads and have in it processed inside kj::EventLoop thread. Semantically equivalent to `asio::io_service::post(f)` and / or `asio::io_service::dispatch(f)` in `asio`.

I failed to find such concept in `kj`. Am I just bad at searching?

I can imagine to implement this on top of `kj::LowLevelAsyncIoProvider`. Create pipe, wrap read fd by `kj::LowLevelAsyncIoProvider::wrapInputFd` and use write fd from other threads. Method `post` moves the handler to heap allocated location and writes heap address to write. Asynchronous read loop in kj EvenLoop reads pointers to handlers, invokes them and releases the heap memory.

@kentonv, are you interested in such functionality upstream? Hints for better approach? Hints for api?

**Comment by kentonv** [comment]
Yeah, currently there is no explicit support for this, but you can use a pipe as you describe.

I do expect to add explicit support at some point. This is why `EventPort` has the `wake()` method. I imagine we would have some separate thread-safe (mutex-protected or lock-free) event queue in each `EventLoop` and then cross-thread events would involve queuing an event there and then calling `wake()` on the `EventPort`. This causes `wait()` or `poll()` in the main thread to return true which hints to the thread that it should check the thread-safe queue (which it would otherwise skip to avoid synchronization overhead).

I haven't quite figured out what the application-facing interface should be here, and I think this will require some design work.

Eventually I want it to be easy to define Cap'n Proto objects tied to threads and then make cross-thread calls the same way you'd make RPC calls.

In any case, I don't think the long-term API is going to be pipe-based; we can do something that performs much better than that. But I'd suggest that for now it probably makes sense for you to stick with pipes rather than try to design this complicated KJ feature...

**Comment by katreniak** [comment]
The pipe based implementation easily hides internal pipe, but it has to expose its dependency on kj::LowLevelAsyncIoProvider. Your vision allows to implement this purely in EventLoop.

The asio::io_service::post API is very handy for thread synchronization. My inteded use case is integration of non-kj code that uses its own threads. But it also allows to move batch tasks to dedicated worker threads and post notification to even loop when the work is ready. Did I understood correctly that you are not interested in this "dirty" solution in `kj`?

**Comment by katreniak** [comment]
My proposal is to add method `kj::AsyncIoProvider::post(kj::Function<void>&& handler)`. 

My implementation uses locked `std::deque<Function<void>>` to queue handlers and write to pipe to notify event loop when dequeu becomes non empty.

**Comment by kentonv** [comment]
Yes, I would prefer not to add the "dirty" solution. There is careful design work that needs to be done here so I don't want to commit to anything prematurely. For now, I believe you can implement what you want as a library on top of KJ using pipes.
