### ISSUE TITLE
Use of noexcept specifier with kj framework

### ISSUE THREAD

**Issue by szenker** [sandstorm-io/capnproto#332]
Assume, we have a function f() which returns a kj::Promise<void>. Does it make sense to declare f() with the noexcept specifier or not?

Example:
```
try
{
  f().then([]()
  {
    <good case>
  }, [](kj::Exception&& ex)
  {
    <bad case 1>
  }
  .wait(...);
}
catch(...)
{
   <bad case 2>
}
```

In most cases, <bad case 1> and <bad case 2> will be probably do exactly the same.

Q: Should functions which return a kj::Promise<> be declared with noexcept specifier to avoid having two different error handling code blocks on the caller side?

`kj::Promise<void> f()`

-- or --

`kj::Promise<void> f() noexcept`

**Comment by kentonv** [comment]
My personal opinion is that the `noexcept` specifier is a misfeature in general, because it is enforced at runtime rather than compile time. If you use it, and then an exception happens that you weren't expecting, the process exits, which is terrible behavior for servers.

But your real question is: should functions that return promises avoid throwing exceptions in favor of returning a broken promise (essentially, an asynchronous exception)? To be honest, I'm not entirely sure. I think there are two possible answers:

1. They should try to use asynchronous exceptions for consistency.
2. It doesn't really matter, because if the calling code is catching exceptions, it should be designed to catch either (e.g. by wrapping in `kj::evalNow()`), and if it isn't catching exceptions (the usual case), then in all likelihood synchronous vs. asynchronous exceptions will result in the same behavior in the end.

While (1) sounds cleaner, it has a problem: It implies that every function which returns a promise probably needs to wrap any synchronous code inside `kj::evalNow()` just in case it throws. That's a lot of annoying boilerplate. So I tend to lean towards (2).

(Closing this because it's not an actionable issue, but happy to continue discussion. Possibly it should move to the mailing list.)
