### ISSUE TITLE
Request: optionally specify maximum size for Text and Data fields in Schema

### ISSUE THREAD

**Issue by ejopony** [sandstorm-io/capnproto#347]
I'd like to be able to specify maximum sizes for blobs in the schema, with both encoding and decoding able to fail early if  the input exceeds this size.

Please correct me if I'm wrong, but I think that at present if I'm expecting a short string, an attacker could instead stick a multi Gb text field onto the line (especially if we're using zlib to compress the transport), crippling the receiving application. Is that correct? To prevent this, I think I'd need to do size checking of the byte stream before passing it to capnproto. Is that true, or is there a better way?

**Comment by kentonv** [comment]
Hi @ejopony,

Cap'n Proto already enforces something called the "traversal limit", which limits the total quantity of data that Cap'n Proto will extract from the message. By default it is 64MiB, although it is configurable. Part of the purpose of the limit is to detect pointer cycles and overlapping content, so the counting happens lazily as you traverse the pointers, hence the name. But, it also prevents plain-old absurdly-sized content. See: https://capnproto.org/encoding.html#amplification-attack

If you want to ensure that the traversal limit is applied upfront (rather than throwing an exception at some random point when you try to read a pointer), you can accomplish this by copying the message into a fresh `MessageBuilder`. The traversal limit is checked as part of performing the copy.

If you'd like to do other kinds of checks, you will need to code them at the application level. Note that you can write generic code to do something like verify the size of all blobs by using the dynamic API (in `dynamic.h`) or even the raw/"any" API (`any.h`). These let you traverse the message generically, independent of the specific message type. If you want to specify different size limits for different fields, you could declare them using [annotations](https://capnproto.org/language.html#annotations), which you can read from the `Schema` objects as you traverse with the dynamic API.

**Comment by ejopony** [comment]
@kentonv,
Thank you so much for that comprehensive response. That does cover everything I was concerned about. Much appreciated!
