### ISSUE TITLE
Exception stack trace is brittle/broken on Mac OS X

### ISSUE THREAD

**Issue by mark-grimes** [sandstorm-io/capnproto#369]
Currently on Mac OS X, an application error printed with KJ_LOG will display something like

    atos[11968]: [fatal] 'pid_for_task' failed: (os/kern) failure (5)

This is triggered at [kj/exception.c++#L113](https://github.com/sandstorm-io/capnproto/blob/d605b498b94d830d2763833d0c7f626156c4ce58/c%2B%2B/src/kj/exception.c%2B%2B#L113) and stops the original error being shown.

The problem happens with both debug and release builds invoked from xcode or the command line.  When tracing through with a debugger the program appears to terminate a few lines down on [kj/exception.c++#L122](https://github.com/sandstorm-io/capnproto/blob/d605b498b94d830d2763833d0c7f626156c4ce58/c%2B%2B/src/kj/exception.c%2B%2B#L122).  I thought it was a permission problem but using "sudo" doesn't help.

I'd suggest disabling the stack trace for Mac OS X if a fix can't be found - currently KJ_LOG is unusable.

**Comment by mark-grimes** [comment]
Just noticed the atos processes hang around and have to be manually killed

**Comment by pqu** [comment]
I've noticed this too -- `atos` will inexplicably hang/fail when called with the PID of a process, but succeeds with the process name/path. I think it started around 10.11 and doesn't happen with every process, but I haven't spent much time looking into what's special about capnp/kj processes.

**Comment by kentonv** [comment]
Hmm, this report is confusing me in multiple ways:

1. This code shouldn't execute in a release build (when NDEBUG is defined while building libkj). So I'm confused about that.
2. KJ_LOG doesn't print stack traces. But maybe you are logging a kj::Exception? Stringifying an exception will indeed invoke this code.
3. If `atos` fails, the effect should only be that the stack trace is missing. The exception description and anything else logged should still show up.

@pqu When you say "process name/path", do you actually mean "executable path"? IIRC on OSX the executable alone is not sufficient due to ASLR.

**Comment by pqu** [comment]
I'm referring to whatever mechanism the `atos` command uses to resolve the [`-o` and `-p` options](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/atos.1.html).

**Comment by kentonv** [comment]
It looks like `-o` wants the executable file. I seem to recall that in the past this didn't work very well because of ASLR.

Ah, on re-reading this thread, I realize: It sounds like the problem is that `atos` is hanging forever, thus blocking the app from making progress. Maybe the solution is a timeout?

**Comment by pqu** [comment]
I just tried a simple test program on Mac OS X 10.11.6 with Xcode 8.0 and couldn't reproduce the issue anymore (nor did it show up when running the tests). @mark-grimes Can you confirm which version of the Xcode tools you're using?

```
#include <kj/debug.h>
#include <kj/exception.h>

int main() {
  kj::Exception e(kj::Exception::Type::FAILED, __FILE__, __LINE__);
  e.extendTrace(0);
  KJ_DBG(e);
}
```

**Comment by mark-grimes** [comment]
Xcode is 7.3 (`Apple LLVM version 7.3.0 (clang-703.0.29)`) but it's a debug build of capnp.  As @kentonv pointed out it doesn't try to print a stack trace if it's not a debug build.  For the program above I get (after having to enter an admin password):

    atos[32778]: [fatal] 'pid_for_task' failed: (os/kern) failure (5)

but don't see atos hanging with `ps -A`.  Not sure if that's because of the simplified code or something fickle in atos.

**Comment by mark-grimes** [comment]
Also note I don't think I've ever seen the code block waiting for atos.  If atos hangs capnp doesn't wait for it so I don't think a timeout will help.

Having said that I only noticed the scores of hanging atos instances long after the tests I was trying, so can't be sure.

**Comment by kentonv** [comment]
The code definitely does wait for atos to complete, or at least waits for it to send EOF on stdout. So I would think if atos hangs then KJ will in fact hang waiting for it.

**Comment by pqu** [comment]
IIRC, something breaks the pipe `popen()` creates before `atos` hangs. Unfortunately, I didn't test this on Xcode 7 before I installed 8. @mark-grimes Are you able to reproduce this issue with the Xcode 8 tools (assuming you can update)?

**Comment by mark-grimes** [comment]
I just upgraded to Xcode 8 and it seems to work fine.  Closing.
