### ISSUE TITLE
AsyncUnixTest::Wake fails on macOS 10.12

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/capnproto#375]
```
$ ./capnp-test -f async-unix-test.c++:556
[ TEST ] kj/async-unix-test.c++:556: legacy test: AsyncUnixTest/Wake
kj/async-unix-test.c++:582: failed: expected port.wait()
stack: 0x109678815 0x1097bfde9 0x109eaa020 0x109ebf9ee 0x109ea8b93 0x109ea8932 0x109ecd103 0x109ebf9ee 0x109ecad25 0x109ea81f0 0x7fffa1e3d255
[ FAIL ] kj/async-unix-test.c++:556: legacy test: AsyncUnixTest/Wake
1 test(s) failed 
```

**Comment by nerdrew** [comment]
Is there going to be a new version published at some point? 0.5.3 was released a bit ago.

**Comment by kentonv** [comment]
@nerdrew We're getting closer. Hopefully before the end of the year. Main problem is that we need to fix up the Windows build in order to do a release, but Sandstorm (parent project of Cap'n Proto) doesn't benefit from Windows, so it's hard to prioritize. Still, #386 and #370 are headed in the right direction.

**Comment by nerdrew** [comment]
Awesome. Thanks.

**Comment by dwrensha** [comment]
Huh. This test passes for me now, on MacOS 10.12.3.

**Comment by kentonv** [comment]
Yay, Apple fixed their bugs... Should we close this, then?
