### ISSUE TITLE
Learning on Tree Way Introductions

### ISSUE THREAD

**Issue by gabomgp** [sandstorm-io/capnproto#383]
Hello. I wish to learn more on Capabilities, and maybe try to implement three party introductions (or Three-way interactions) in capnproto-rust. For me and other that wish to learn, ¿Can you recommend papers, implementations, documentation to understand this complex subject?

**Comment by kentonv** [comment]
Hi @gabomgp,

I suspect Mark S. Miller and others have written papers on this subject, but I'm not personally very familiar with the literature. I mostly picked it up by talking to them directly.

I'd start by reading the comments in [rpc.capnp](https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/rpc.capnp), which are intended to be a full specification of the protocol. You'll also find in there many links to erights.org, which is Mark Miller's site where he has written a great deal about CapTP (an older protocol which Cap'n Proto is based on) and capabilities in general. Unfortunately the site is not terribly well-organized and is incomplete in many places.

On another note, this discussion probably makes more sense as a mailing list thread. I am going to close this issue since it is not tracking a specific action item. Please feel free to start a thread instead, at: https://groups.google.com/group/capnproto
