### ISSUE TITLE
Limited Mutation Support

### ISSUE THREAD

**Issue by llchan** [sandstorm-io/capnproto#390]
The docs/news mention that mutation is not supported because messages are arena-allocated. It would be useful to allow a limited set of mutations if they can be done in-place. For example, if I am just modifying primitive values, they can be mutated and the existing encoded message can be sent out. Mutation in general is useful if the caller has some knowledge of what parts of the message changed and only needs to update those portions, rather than rebuilding the whole message from scratch.

For what it's worth, Flatbuffers support this by having mutation methods return a bool indicating success, and if it's unsuccessful the caller rebuilds the message from scratch.

What do you guys think? Is this feasible? Given my (limited) understanding of the encoding I would think it's doable for primitive fields.

**Comment by kentonv** [comment]
Hi Lawrence,

Actually, mutation is supported, it just isn't always efficient. If a change requires re-allocating an object, then the space where the object lived previously "leaks" -- it is no longer used but cannot be reused. In some cases these leaks are not a big deal and can be ignored. Or, it can work to periodically "garbage collect" the leaks by making a complete copy of the message.

Another catch to mutation is that it's tricky to mutate a message that wasn't originally built in-process. That is, if you receive a message over the network or read it from disk, you normally need to make one copy before you can mutate it at all. You can avoid this copy by creating a custom subclass of MessageBuilder which is initialized with existing data, using this constructor:

https://github.com/sandstorm-io/capnproto/blob/ce5d90bd341db112b8a26f4d864ac26edc8a376a/c++/src/capnp/message.h#L164

However, as discussed in the comments, this constructor is only suitable to use with trusted input. With untrusted input, it is necessary to read into a Reader first and then copy the content into a Builder as a way to validate it.

I'm marking this closed since I think this is the best we can do here, but if you have further questions or ideas feel free to reply or start a thread on the mailing list.

**Comment by llchan** [comment]
Not sure or if I missed this in the docs or if it's an undocumented feature but this points me in the right direction. Thank you!
