### ISSUE TITLE
capnp homebrew package broken

### ISSUE THREAD

**Issue by abe-winter** [sandstorm-io/capnproto#391]
Hi,

Not sure if this is the right place for this bug. The `capnp` homebrew package has a bad dependency and fails to install. Details:
```
         error: downloading 'http://googletest.googlecode.com/files/gtest-1.7.0.zip' failed
```
See also https://groups.google.com/forum/#!msg/capnproto/1BBK4rcRlHA/Kwu3NvK8BQAJ, which recommends changing the dep to https://github.com/google/googletest/archive/release-1.7.0.zip.

**Comment by paulproteus** [comment]
Hi @abe-winter !

I think this will need to be fixed in the `Homebrew/homebrew-core` repo. You can see a discussion here: https://github.com/Homebrew/homebrew-core/issues/5435

I think that's the best place to track these changes, so for now I'll close this issue. If you think we should re-open it here, please let me know! I'm grateful you took the time to ping us; it reminded me how important it is to help the Homebrew people know how to move forward with fixing https://github.com/Homebrew/homebrew-core/issues/5435 , which I just did.

Thanks again!
