### ISSUE TITLE
Forwarding RPC request to peer RPC

### ISSUE THREAD

**Issue by sergei-dyshel** [sandstorm-io/capnproto#393]
I have an RPC server which holds client of peer server (of same type, same capnp schema).
Sometimes I want to forward request to peer server. The logical way of doing this as I see is:
```c++
kj::Promise<void> forward(DoSmthRequestContext context) {
    auto peer_request = peer->doSmthRequest();
    request.set(context.getParams());
    return request.send().then([=](Response......   response) 
        { context.setResults(response); return kj::READY_NOW; });
}
```

The problem is that request class which is subclass of `Params::Builder`, does not have method to set all fields at once, so I have copy all fields one by one.

 Is this correct way of forwarding requests?

PS. Using version 0.6

**Comment by dwrensha** [comment]
Hi!

One way to accomplish that is through [`Capability::Client::typelessRequest()`](https://github.com/sandstorm-io/capnproto/blob/08295ff221df27f6a0a0fe8dbfad9d385e3f6f15/c%2B%2B/src/capnp/capability.h#L204-L208), which gives you an `AnyPointer::Builder` that you can set to anything:

```c++
   auto req = peer->typelessRequest(
       capnp::typeId<DoSomethingInterface>(), methodNumber, nullptr);
   req.setAs(context.getParams());
   req.send().then(...);
```
As you can see, this approach does require you to manually specify the type ID and method number.

Can we do better? Well, it's tempting to say that we should add a method to `Request<Params, Results>`:

```c++
  void copyContentFrom(ReaderFor<Params> value);
```

but note that this would necessarily have the same caveats as `StructBuilder::copyContentsFrom()`, i.e.

```
  void copyContentFrom(StructReader other);
  // Copy content from `other`.  If `other`'s sections are larger than this, the extra data is not
  // copied, meaning there is a risk of data loss when copying from messages built with future
  // versions of the protocol.
```

because once we've set `auto peer_request = peer->doSmthRequest()`, it's already too late for `peer_request` to allocate more space for its top-level struct. So if the caller is using a newer version of the schema, we might lose data.

This suggests that maybe the generated `doSmthRequest()` method should take an optional `Params::Reader` argument which would be used to initialize the `Params` builder. Note, however, that `doSmthRequest()` already takes an optional `sizeHint` parameter, so allowing another optional parameter would probably mean generating separate methods. The question here is: would the benefit be worth the extra generate code?

**Comment by sergei-dyshel** [comment]
Thank you for explanation! Now I see that things are not that easy, for now I'll just stick with one-by-one assignment.

**Comment by kentonv** [comment]
Seems like this got answered as well as it could have, so I'm closing it...
