### ISSUE TITLE
A benchmark of RPC libraries

### ISSUE THREAD

**Issue by sztomi** [sandstorm-io/capnproto#400]
I'm making a benchmark of RPC libraries to compare [rpclib](http://rpclib.net) to other RPC solutions. It is very much a work in progress, but I wanted to ask for your input about my benchmark implementation using capnproto. The benchmark is simple: perform a synchronous call to a simple function that takes an int and returns an int, and decode the return value so that the result is available in an int variable. My intention is to implement the benchmark with each library as efficiently as possible, so any input about possible optimizations is welcome.

```cpp
#pragma once

#ifndef FIXTURE_H_NNOJDJZG
#define FIXTURE_H_NNOJDJZG

#include "benchmark/benchmark.h"

#include "capnp/ez-rpc.h"

#include "target_code.h"

#include "capnp/capnp_service.capnp.h"

class capnp_server : public CapnpServiceBenchmark::Server {
public:
  kj::Promise<void> getAnswer(GetAnswerContext context) override {
    auto num = context.getParams().getNumber();
    context.getResults().setResult(::get_answer(num));
    return kj::READY_NOW;
  }
};

class capnp_bench : public benchmark::Fixture {
public:
  capnp_bench()
      : server(kj::heap<capnp_server>(), "127.0.0.1:8081"),
        client_thing("127.0.0.1:8081"),
        client(client_thing.getMain<CapnpServiceBenchmark>()) {
    auto &wait_scope = server.getWaitScope();
    server.getPort().wait(wait_scope);
  }

  void get_answer() {
      auto request = client.getAnswerRequest();
      request.setNumber(23);
      auto resultPromise = request.send();
      int a;
      benchmark::DoNotOptimize(
          a = resultPromise.wait(client_thing.getWaitScope()).getResult());
  }

  ~capnp_bench() noexcept {}

  capnp::EzRpcServer server;
  capnp::EzRpcClient client_thing;
  CapnpServiceBenchmark::Client client;
};

#endif /* end of include guard: FIXTURE_H_NNOJDJZG */
```

PR is also welcome: https://github.com/rpclib/benchmarks/blob/master/include/capnp/fixture.h

**Comment by kentonv** [comment]
Hi @sztomi,

The code looks reasonable.

Keep in mind, though, that in these very simple benchmark cases, Cap'n Proto is likely to appear to perform poorly. The case does not exercise any of the situations where Cap'n Proto excels, such as:

* Larger, more complicated payloads, where most RPC systems will spend a lot of time on parsing / serialization, but Cap'n Proto will not.
* Multi-step communications, involving a series of dependent method calls, where Cap'n Proto's promise pipelining reduces the number of network round trips needed. (You also need non-negligible network latency to show this advantage, which a local test won't have.)
* Cases involving lots of concurrent activity, where Cap'n Proto's asynchronous event loop becomes necessary.

In very trivial cases, Cap'n Proto is actually expected to perform poorly, because it is doing a bunch of extra bookkeeping to make the above cases work well but that bookkeeping doesn't end up providing any advantage. For example, when you're only making one request at a time, using an async even loop adds tons of memory allocation and switching overhead that brings no advantage. But as soon as you have two simultaneous requests, this infrastructure becomes necessary.

So, the result of your benchmark may be misleading: It will show a more trivial RPC systems to be "faster", even though in real-world use cases their limitations would in fact make them much less efficient.

What would be really cool is if someone came up with a more complicated but realistic test case, involving multiple nodes in a distributed system (on a real network) performing complex, concurrent interactions -- and then write that using multiple RPC systems. But it's a lot of work, which is probably why we are lacking in great benchmarks today. :/

**Comment by sztomi** [comment]
Thank you very much. If you have any suggestions for other benchmarks, please let me know.

**Comment by sztomi** [comment]
hey @kentonv, I've completed my benchmark suite and analysis, you might be interested in the results: http://szelei.me/rpc-benchmark-part1/

(actually I'd be really interested in your input about how capnp is faster than direct calls in the 3rd benchmark!)

**Comment by kentonv** [comment]
Hi Tamás,

I'm pretty sure the get_blob benchmarks couldn't be correct. Let me take a look and get back to you.

**Comment by kentonv** [comment]
Hi Tamás,

I hate to break this to you, but it appears there is a serious problem in your measurement methodology. All your graphs are  based on the "CPU" column as output by google-benchmark. This column counts only _userspace_ CPU time, while ignoring _system_ CPU time (i.e. time spent in syscalls). For an I/O benchmark, this is inappropriate, since syscalls are an important part of the overall time. You should probably be using google-benchmark's "Time" (i.e. real time) column instead.

If you look at the combination of userspace and system CPU time (or just look at real-time, which is approximately equal to this sum if the system is not under external load), then Cap'n Proto ends up approximately twice as fast as rpclib in the large get_blob benchmark cases, at least on my machine.

It's not entirely clear to me why rpclib spends so much more time in kernel space than other RPC systems do. Perhaps it is using `writev()` to push the byte gathering/copying into the kernel?

**Comment by kentonv** [comment]
@sztomi Regarding Cap'n Proto being faster than "direct" in the struct case, I think this is because "direct" is actually making a copy of a deeply-nested C++ data structure containing std::vectors and stuff. That involves a bunch of malloc() and free(). The Cap'n Proto case, on the other hand, is copying a Cap'n Proto structure into a message, where the space for the message is a contiguous segment of memory. It probably only malloc()s a couple times.

If I'm right, this is Cap'n Proto working as intended.

That said, I'd suggest running the test cases under a CPU profiler to see if anything jumps out.

**Comment by sztomi** [comment]
Hi Kenton,

Thanks for taking a look in detail. 

> All your graphs are based on the "CPU" column as output by google-benchmark

No, that's not true. In fact, for each benchmark case I display a "cpu time" and a "wall clock" (real) time graph. I made sure that minimal extra processes were running to avoid distorting the real times. Apologies for the formatting not making this more obvious, I probably should have used some sort of visual indication as well.

> It's not entirely clear to me why rpclib spends so much more time in kernel space than other RPC systems do. Perhaps it is using writev() to push the byte gathering/copying into the kernel?

Actually, me neither - most likely it's something similar to your guess, but I'll have to dive into asio code with a profiler to find out.

> The Cap'n Proto case, on the other hand, is copying a Cap'n Proto structure into a message, where the space for the message is a contiguous segment of memory. It probably only malloc()s a couple times.

Wow, that's very nice. Thanks for the explanation.

> Actually, another problem with the struct case is that Cap'n Proto is using different randomly-generated data from other fixtures.

Fair point. Though I don't think it makes a huge difference either, because the lengths are the same (number of fields, length of strings etc.), and the random generator is the same.

**Comment by kentonv** [comment]
@sztomi Oops, indeed, I didn't read carefully enough, but I see now that you have two sets of graphs. Sorry!

I think, though, that the CPU time graphs are misleading if they do not include kernel time, so my opinion is that they don't belong in the blog post. People (like me, apparently!) will often skim through the graphs without fully reading the text and may end up with the wrong impression.

BTW, random comment from your post:

> This reveals a weird jump in cpu times around the 256k mark for rpclib

FWIW, one common reason for such jumps is when the working set exceeds one of the CPU's caching levels. For example, 256kB is a common size for an L2 cache. If your working set (the subset of RAM actively accessed by the CPU) in one benchmark iteration is under 256kB, then it will stay cached in L2 from iteration to iteration. If it goes just over 256kB, then the LRU caching algorithm will likely cause the whole set to be purged from L2 and reloaded from L3 every time around the loop, making the whole L2 cache essentially worthless and slowing everything down. This is a funny quirk of microbenchmarking -- since you have a tight loop that is iterating over the same data set repeatedly, and so the data may already be in cache from the previous iteration, if it's small enough. In the real world you would normally process each message once and so would not expect it to be cached at all.

**Comment by sztomi** [comment]
> I think, though, that the CPU time graphs are misleading if they do not include kernel time, so my opinion is that they don't belong in the blog post. 

I do think that they reveal a certain facet of the performance of the implementation, but I can see where you are coming from. I plan to redo this benchmark in a year or so, and I'll make sure that I avoid any confusion.

> FWIW, one common reason for such jumps ...

Thank you, great explanation. Every time I performance comes up, caching causes something unexpected. It's a fascinating subject, I'll have to read up on it.

**Comment by KubaO** [comment]
When I implement such benchmarks, I instrument the networking code to attach a virtual "network hop barrier" to the first byte of each `write` to a socket, and that barrier propagated to any use of the data past that byte-referenced barrier on the receiver end, so that in the traces it's very clear that a certain number of network hops separates the call request, method execution, return, finish, etc. The network hops each way are traced separately, so it's very easy to massage the trace to e.g. set a weight of 0 to wall time, and have a custom weight to each direction of a hop across a particular network, to investigate protocol performance based on I/O latencies alone. Asymmetric links are easy this way, and simplistic protocols have no way to cheat: their excessive network hopping costs are immediately apparent.
