### ISSUE TITLE
Memory leak when using evalLater

### ISSUE THREAD

**Issue by barakp** [sandstorm-io/capnproto#425]
Hi @kentonv 
This small function leads to a memory leak when being run:
```cpp
  kj::Promise<void> IncCounter()
  {
    ++counter_;
    return kj::READY_NOW;
  }

  kj::Promise<void> EvalLaterNeverDone()
  {
    return kj::evalLater(
      [this]() {
        ++counter_;
        return IncCounter().then(
          [this]() {
            return kj_timer_.afterDelay(kj::MICROSECONDS).then(
              [this]() {
                return EvalLaterNeverDone();
              });
          },
          [this](kj::Exception &&e) {
            return kj_timer_.afterDelay(kj::MICROSECONDS).then(
              [this]() {
                return EvalLaterNeverDone();
              });
          });
      }).catch_(
        [this](kj::Exception &&e) {
          return kj_timer_.afterDelay(kj::MICROSECONDS).then(
            [this]() {
              return EvalLaterNeverDone();
            });
      });
  }
```

However removing the call to `evalLater` or the error handler from the `IncCounter().then(...)` doesn't result in a memory leak. What exactly is wrong with my use of promises here?

**Comment by kentonv** [comment]
The problem is that you are actually creating an ever-expanding chain of error handlers with `.catch_()`. If an exception were thrown after, say, 300 iterations, then the `.catch_()` handler from iteration 300 would receive the exception, but if it also threw, then the one from iteration 299 would get a crack at it, and so on. Thus every one of these error handlers has to stay resident in memory forever in case it is needed.

Try this instead:

    kj::Promise<void> EvalLaterNeverDoneLoop()
    {
      return kj::evalLater(
        [this]() {
          ++counter_;
          return IncCounter().then(
            [this]() {
              return kj_timer_.afterDelay(kj::MICROSECONDS).then(
                [this]() {
                  return EvalLaterNeverDoneLoop();
                });
            },
            [this](kj::Exception &&e) {
              return kj_timer_.afterDelay(kj::MICROSECONDS).then(
                [this]() {
                  return EvalLaterNeverDoneLoop();
                });
            });
        });
    }

    kj::Promise<void> EvalLaterNeverDone()
    {
      return EvalLaterNeverDoneLoop().catch_(
          [this](kj::Exception &&e) {
            return kj_timer_.afterDelay(kj::MICROSECONDS).then(
              [this]() {
                return EvalLaterNeverDone();
              });
        });
    }

This way, only the first call to `EvalLaterNeverDone()` registers an error handler, rather than adding another one for every iteration. Then, tail-call optimization can kick in.

(It still looks to me like there is some redundant error handling here but at least it shouldn't leak anymore.)

**Comment by sergei-dyshel** [comment]
@kentonv, I have some questions regarding your explanation. 

By *tail-call optimization* did mean the logical refactoring you did to @barakp's  code, not the well-known [compiler optimization](http://wiki.c2.com/?TailCallOptimization), since the later does not apply here IMHO?

Also, AFAIU the real problem is error handler added by `catch_` on every recursive call. If that's the case, why the modified code by @barakp which still features that problematic `catch_` and looks like 
```c++
kj::Promise<void> EvalLaterNeverDone()
  {
    return kj::evalLater(
      [this]() {
        ++counter_;
        return IncCounter().then(
          [this]() {
            return kj_timer_.afterDelay(kj::MICROSECONDS).then(
              [this]() {
                return EvalLaterNeverDone();
              });
          });
      }).catch_(
        [this](kj::Exception &&e) {
          return kj_timer_.afterDelay(kj::MICROSECONDS).then(
            [this]() {
              return EvalLaterNeverDone();
            });
      });
  }
```

does not leak?

**Comment by kentonv** [comment]
@sergei-dyshel KJ promises implement a form of tail-call optimization specifically for promises: If a .then() callback returns a new promise, tail call optimization applies, so that you don't get an ever-expanding list of promises when you implement a recursive promise loop. This is important because recursion is really the only way to implement loops in asynchronous code. This optimization is not the same thing as the compiler optimization (which applies to synchronous recursive calls), but it is the same concept.

The code you posted should still leak, as far as I can tell.
