### ISSUE TITLE
Enable APCs on Windows since all other available cross-thread signaling is overcomplicated

### ISSUE THREAD

**Issue by nneesshh** [sandstorm-io/capnproto#435]
Just as title, is "paf.fulfiller->fulfill()" thread safe?
I write signal handler as follows:

void signal_handler(int sig) {
  g_paf.fulfiller->fulfill();
}

Then I register signal:

        //
	signal(SIGINT, signal_handler);
	signal(SIGTERM, signal_handler);
#ifdef SIGBREAK
	signal(SIGBREAK, signal_handler);
#endif

But the signal handler was triggered by another thread on windows.
So I need to confirm if the promise fulfill() or reject() method is thread safe.
If it is not, must I add a mutex on it?

**Comment by kentonv** [comment]
Sorry, it is not thread-safe. In general, KJ and Cap'n Proto methods are only thread-safe if they are "const" (and not very many things are const).

A mutex won't work here because it's not just the fulfiller that needs to be protected, but the entire event loop. Note also that fulfilling a promise from another thread inherently requires a different implementation than same-thread since if the receiving thread is asleep, it needs to be woken somehow. Eventually I would like to add explicit support for this, but it's a non-trivial chunk of work an hasn't happened yet.

For now, what you will need to do instead is have the threads communicate using one of the OS primitives supported by the KJ event loop. On Unix, a pipe or a signal would work. It sounds like you're using Windows, though. Currently, on Windows, the KJ event loop only supports objects that can be registered with an IO completion port, which is only objects that use overlapped I/O. Win32 unnamed pipes (created with CreatePipe()) don't support this. You could use a loopback network connection or a named pipe (CreateNamedPipe()).

Currently in the windows event loop we use GetQueuedCompletionStatus() instead of GetQueuedCompletionStatusEx(). If we used the latter instead, we could wait in an alertable state, meaning you could use an APC, which would be *much* easier than a named pipe or socket. The main reason I didn't use it is because Wine doesn't implement it, but maybe that's not a good reason. If you think this would be a good idea, I'd accept a patch to change this.

**Comment by nneesshh** [comment]
Hi, @kentonv, thanks for your prompt explanation. You are really nice and professional.
I don't know much about APC, but I think notifying cross thread is a cool idea, just like uv_async_send in libuv. Sometimes we do tasks in threads other than the main thread, but how to post result data back to main thread is not simple enough. uv_async_send can solve the case, and keep us doing work only in one thread.
If KJ can support the same like feature, I think it will be very cool and helpful.

best regards

**Comment by kentonv** [comment]
APCs are a Windows feature for scheduling some function to run in another thread. See:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms684954(v=vs.85).aspx

But it requires changing KJ's code to use GetQueuedCompletionStatusEx() instead of GetQueuedCompletionStatus().

Unfortunately I'm not sure if/when I'll have a chance to work on this myself (I don't even have a Windows machine at work), but I'll leave this bug open for it.
