### ISSUE TITLE
GCC build broken

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/capnproto#442]
Somehow e6e2912225b9bd772114b7b400f71517e5067118 broke the GCC build. It works in Clang, but GCC now crashes when invoking `capnp compile`, deep in the parsing code. Investigating...

**Comment by kentonv** [comment]
@harrishancock This may affect MSVC, too. I recall you found MSVC was having trouble with the parser code, but I can't remember what kind of trouble. Here it was crashing because it turns out the intrinsics I was using to detect when array copies could fall back to memcpy() was wrong: it was right for GCC 4 but wrong for GCC 5 and Clang, though the code had a special-case for Clang. I didn't see any `#if _MSC_VER`s around so I think MSVC was compiling the same branch as GCC, and could have had the same problem.

**Comment by harrishancock** [comment]
The main problem MSVC has with the parser code is unrelated: `parse::anyOfChars()` causes an ICE. For some versions of Visual C++ I was able to work around the ICE and build it, and noticed that the `capnp` compiler intermittently crashed on exit (~1 in 20 runs), but otherwise worked correctly.

It's probably high time I tried compiling full capnproto with VS2017, now that it's out. Will report how it goes.
