### ISSUE TITLE
c++/src/capnp/compiler/capnpc-c++.c++: PVS-Studio: The expression is excessive or contains a misprint

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [sandstorm-io/capnproto#446]
We have found a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

We suggests having a look at the emails, sent from @pvs-studio.com.

Analyzer warning: [V590](https://www.viva64.com/en/w/V590/) Consider inspecting this expression. The expression is excessive or contains a misprint. capnpc-c++.c++ 1523

**capnpc-c++.c++:**
```
DiscriminantChecks makeDiscriminantChecks(....)
{
  ....
  bool shouldIncludeStructInit =
    kind == FieldKind::STRUCT || kind == FieldKind::BRAND_PARAMETER;
  bool shouldIncludeSizedInit =
    kind != FieldKind::STRUCT || kind == FieldKind::BRAND_PARAMETER; // <=
  ....
}
```
Useful article: [Logical Expressions in C/C++. Mistakes Made by Professionals](https://www.viva64.com/en/b/0390/).

**Comment by kentonv** [comment]
Thanks for the report.

While it's true that the right-hand side of the expression is redundant, the logic is in fact correct. This happened because when BRAND_PARAMETER was added, all of these booleans needed to be true for it, so `|| kind == FieldKind::BRAND_PARAMETER` was appended to all of them.
