### ISSUE TITLE
Immediately execute lambda expression attached via then()

### ISSUE THREAD

**Issue by szenker** [sandstorm-io/capnproto#459]
Hi,

I have the following code example:

```
  EventLoop loop;
  WaitScope waitScope(loop);
  auto pair = newPromiseAndFulfiller<int>();
  auto promise = pair.promise.then([](int i){
	  printf("hello\n");
	  return 77;
  }).then([](int i){
	  printf("world\n");
  });
  promise.detach([](kj::Exception&&){});

  pair.fulfiller->fulfill(10);

  loop.run(100000);
```

In this example, "hello" "world" will be printed while executing `loop.run()`. Is there a possibility to already execute those two callbacks during `pair.fulfiller->fulfill(10)` gets executed? Basically immediately when the promise gets resolved and not with the next EventLoop run?

**Comment by kentonv** [comment]
This would violate an important guarantee about continuation callbacks: they always execute with nothing else on the stack. This is important because it allows the callback to assume e.g. that no mutexes are locked and that all data structures are in a consistent state (they aren't being modified up-stack).

In order to allow synchronous execution, we'd need to introduce a new version of `.then()` which explicitly opts into this, e.g. `.thenSynchronous()`. I'm not sure this would be worthwhile -- what is the use case?

If you specifically want a fulfiller that executes certain logic when `fulfill()` is called, keep in mind that `PromiseFulfiller` is an abstract class. You can implement your own subclass with arbitrary logic in `fulfill()` and pass that off instead.

**Comment by kentonv** [comment]
Closing this for now, but I'd be interested to know more about your use case.
