### ISSUE TITLE
Compilation issue on MSVC

### ISSUE THREAD

**Issue by hof** [sandstorm-io/capnproto#479]
Created a simple capnproto program that uses generic types in the message schema. See https://github.com/hof/capnp_test 

This causes compile errors on MSVC 2015 and 2017, See: https://ci.appveyor.com/project/hof/capnp-test/build/1.0.2/job/qa5cvfk75dxu33t9#L4592

But not on Linux g++ and clang, See https://travis-ci.org/hof/capnp_test/jobs/232762510 

Am I making a mistake here? Suggestions? Thanks

**Comment by harrishancock** [comment]
Thanks for the report! I'll see about reproducing this, but my hunch is it's another compiler bug we'll need to work around.

Couple quick things:

1. Both of your appveyor jobs are using vs2017. You'll need to add `-G "%CMAKE_GENERATOR%"` to your build script's configure step in order to test both.

2. Thank you for hunterizing CapnProto!

Will get back to you once I reproduce.

**Comment by hof** [comment]
Thanks. I updated the appveyor config.

**Comment by harrishancock** [comment]
@hof I have reproduced this and have an idea for a fix. The problem seems to have to do with MSVC's limited constexpr support.

**Comment by harrishancock** [comment]
This bug's back. MSVC 14.13.26128 (from the latest version of VS2017, which AppVeyor now uses) has a regression which causes this exact same build failure, even with our workaround from #489.
