### ISSUE TITLE
The capnproto.org site does not mention 0.6.0 release, no way to release post

### ISSUE THREAD

**Issue by Spice-King** [sandstorm-io/capnproto#484]
The site appears to make no mention of the 0.6.0 release. The [news page](https://capnproto.org/news/) does not list the release post, which [does exist](https://capnproto.org/news/2017-05-01-capnproto-0.6-msvc-json-http-more.html).

I only managed to find it via looking at the sources and there is also a tweet that points to it. I generated a local copy of the site from the doc folder with `jekyll` and found other things that were not updated, like the Installation page's comment on Windows support, the rewritten Road Map page, and probably others.

Might help with the discoverability of that release with people who just assume a new release will show up on the site.

That said, thanks for the work on the full Windows support, I might actually dust off one of my planned side projects/learning experiments some time in the next month.

**Comment by Spice-King** [comment]
Saw the site was fixed some time ago. Closing.

**Comment by kentonv** [comment]
Ugh.

Apparently when I added a slide deck to the site for my talk on 5/18 I accidentally branched from the 0.5.x version of the site. As a result, everything got reverted -- except for the 0.6 release announcement blog post, which was a new file, and so didn't get deleted, since the update script only overwrites files.

Someone pointed this out on twitter yesterday and I fixed it. I wish I'd noticed your bug report earlier but somehow it slipped past me. :(
